import {
  Link,
  QrCode,
  Type,
  FileText,
  Key,
  FileCode,
  Palette,
  Code,
  FileType,
  Ruler,
  Table,
  Image,
  StickyNote,
  Dice1Icon as Dice,
  Calculator,
  Clock,
  Hash,
  Regex,
  Grid3X3,
} from "lucide-react"

export const tools = [
  {
    name: "All Utilities",
    description: "View all available tools in one place",
    summary: "Browse the complete collection of utilities",
    href: "/all",
    icon: <Grid3X3 className="h-5 w-5" />,
  },
  {
    name: "URL Shortener",
    description: "Shorten long URLs for easier sharing",
    summary: "Create and manage shortened URLs using browser storage",
    href: "/url-shortener",
    icon: <Link className="h-5 w-5" />,
  },
  {
    name: "QR Code Generator",
    description: "Generate QR codes for any text or URL",
    summary: "Create downloadable QR codes for websites, text, and more",
    href: "/qr-generator",
    icon: <QrCode className="h-5 w-5" />,
  },
  {
    name: "Text Case Converter",
    description: "Convert text between different cases",
    summary: "Transform text to uppercase, lowercase, title case, and more",
    href: "/text-case",
    icon: <Type className="h-5 w-5" />,
  },
  {
    name: "Word Counter",
    description: "Count words, characters, and paragraphs",
    summary: "Analyze text with real-time statistics and insights",
    href: "/word-counter",
    icon: <FileText className="h-5 w-5" />,
  },
  {
    name: "Password Generator",
    description: "Create secure random passwords",
    summary: "Generate strong passwords with customizable options",
    href: "/password-generator",
    icon: <Key className="h-5 w-5" />,
  },
  {
    name: "Base64 Encoder/Decoder",
    description: "Convert text to and from Base64",
    summary: "Encode and decode Base64 strings with ease",
    href: "/base64",
    icon: <FileCode className="h-5 w-5" />,
  },
  {
    name: "Color Picker",
    description: "Select and convert between color formats",
    summary: "Choose colors and get HEX, RGB, and HSL values",
    href: "/color-picker",
    icon: <Palette className="h-5 w-5" />,
  },
  {
    name: "JSON Formatter",
    description: "Format and validate JSON data",
    summary: "Beautify, validate, and analyze JSON with syntax highlighting",
    href: "/json-formatter",
    icon: <Code className="h-5 w-5" />,
  },
  {
    name: "Markdown Converter",
    description: "Convert Markdown to HTML",
    summary: "Transform Markdown syntax to HTML with live preview",
    href: "/markdown",
    icon: <FileType className="h-5 w-5" />,
  },
  {
    name: "Unit Converter",
    description: "Convert between different units of measurement",
    summary: "Convert length, weight, temperature, and more",
    href: "/unit-converter",
    icon: <Ruler className="h-5 w-5" />,
  },
  {
    name: "CSV to JSON Converter",
    description: "Convert CSV data to JSON format",
    summary: "Transform CSV files or text into structured JSON data",
    href: "/csv-to-json",
    icon: <Table className="h-5 w-5" />,
  },
  {
    name: "Image Compressor",
    description: "Compress images in your browser",
    summary: "Reduce image file sizes without leaving your browser",
    href: "/image-compressor",
    icon: <Image className="h-5 w-5" />,
  },
  {
    name: "Note Keeper",
    description: "Take and save notes locally",
    summary: "Create, edit, and organize notes with browser storage",
    href: "/note-keeper",
    icon: <StickyNote className="h-5 w-5" />,
  },
  {
    name: "Random Generator",
    description: "Generate random values",
    summary: "Create random numbers, strings, UUIDs, and more",
    href: "/random-generator",
    icon: <Dice className="h-5 w-5" />,
  },
  {
    name: "Calculator",
    description: "Perform calculations",
    summary: "Basic and scientific calculator with history",
    href: "/calculator",
    icon: <Calculator className="h-5 w-5" />,
  },
  {
    name: "Time Zone Converter",
    description: "Convert times between time zones",
    summary: "Compare times across different global locations",
    href: "/time-zone",
    icon: <Clock className="h-5 w-5" />,
  },
  {
    name: "Hash Generator",
    description: "Generate hash values for text",
    summary: "Create MD5, SHA-1, SHA-256, and other hash values",
    href: "/hash-generator",
    icon: <Hash className="h-5 w-5" />,
  },
  {
    name: "Regex Tester",
    description: "Test regular expressions",
    summary: "Build and test regular expressions with real-time matching",
    href: "/regex-tester",
    icon: <Regex className="h-5 w-5" />,
  },
]

